name: apple
description: "Apple Fruits Grocery Cart Project"
publish_to: 'apple.qrdpro.com'

version: 2025.01.19+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  http: ^1.2.2
  intl: ^0.18.0
  badges: ^3.1.2
  sqflite: ^2.4.1
  provider: ^6.1.2
  path_provider: ^2.1.5
  dropdown_search: ^5.0.6
  shared_preferences: ^2.3.1
  cached_network_image: ^3.4.1
#  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - images/

